/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NestedIndexRouteImport } from './routes/nested/index'

const NestedIndexRoute = NestedIndexRouteImport.update({
  id: '/nested/',
  path: '/nested/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/nested/': typeof NestedIndexRoute
}
export interface FileRoutesByTo {
  '/nested': typeof NestedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/nested/': typeof NestedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/nested/'
  fileRoutesByTo: FileRoutesByTo
  to: '/nested'
  id: '__root__' | '/nested/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NestedIndexRoute: typeof NestedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nested/': {
      id: '/nested/'
      path: '/nested'
      fullPath: '/nested/'
      preLoaderRoute: typeof NestedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  NestedIndexRoute: NestedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
